"""
Event Cascade Visualization Test Script
=======================================

This script demonstrates how to visualize a financial event cascade using the EventCascadeVisualizer.
It loads a JSON file containing the reconstructed event data (EventCascade) and generates a
timeline visualization image.

Usage:
    Run this script from the project root directory:

    Run:
    python examples/uTEST/Builder/test_viz.py

Requirements:
    - matplotlib
    - pandas
    - numpy
    - The project environment must be set up correctly (finmy package accessible).
"""

import os
import json
import matplotlib.pyplot as plt
from finmy.builder.agent_build.visualizer import EventCascadeVisualizer

# Use 'Agg' backend for matplotlib to support running in headless environments (no GUI required)
plt.switch_backend("Agg")


def test_visualization():
    """
    Main function to run the visualization test.

    Steps:
    1. Define path to the input JSON file (IntegratedEventCascade.json).
    2. Load the JSON data.
    3. Initialize the EventCascadeVisualizer.
    4. Generate and save the visualization to a PNG file.
    """

    # --- 1. Define Input Data Path ---

    # We use the experimental data generated by the StepBuilder
    # Path is relative to the project root
    json_path = "EXPERIMENT/uTEST/StepBuilder/IntegratedEventCascade.json"

    # Check if the input file exists
    if not os.path.exists(json_path):
        print(f"Error: JSON file not found at {json_path}")
        print(
            "Please ensure you are running this script from the project root and the data exists."
        )
        return

    # --- 2. Load JSON Data ---
    print(f"Loading event cascade data from: {json_path}")
    with open(json_path, "r", encoding="utf-8") as f:
        cascade_data = json.load(f)

    # --- 3. Initialize Visualizer ---
    print("Initializing EventCascadeVisualizer...")
    viz = EventCascadeVisualizer()

    # --- 4. Generate Visualization ---

    # Output path for the image (saved in the same directory as the input json)
    output_path = os.path.join(os.path.dirname(json_path), "test_timeline.png")

    print(f"Generating visualization to: {output_path}...")
    try:
        # Call the plotting function
        viz.plot_cascade(cascade_data, output_path)

        # Verify output generation
        if os.path.exists(output_path):
            print(f"Success: Visualization successfully generated at {output_path}")
        else:
            print("Error: Output file was not created.")

    except Exception as e:
        print(f"Exception occurred during visualization: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    test_visualization()
